### ISSUE TITLE
No diagnosegruppestreng in acute outpatient visits

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-feature-generation#136]
Thread: https://aarhuspsychia-vs65733.slack.com/archives/C046T41LP0B/p1674827658227459

If no such column exists, we should just look at the `diagnosekode` column. This requires moving `code_col_name` into the `diagnoses_source_table_info` in `load_diagnoses.py`.

**Comment by sarakolding** [comment]
maybe this is no longer relevant, since we don't use that table anymore?

**Comment by MartinBernstorff** [comment]
Assuming outpatient visits are contained in the "contacts" table, I agree. Closing - please reopen if that's not the case :-)
