### ISSUE TITLE
Debug deepcheck error in feature_generation in repo: psycop_forced_admissions

### ISSUE THREAD

**Issue by erikperfalk** [Aarhus-Psychiatry-Research/psycop-feature-generation#38]
Deepchecks gives an error when generating features from this [branch](https://github.com/Aarhus-Psychiatry-Research/psycop-forced-admissions/tree/erperf/features_structured_SFI)

File: generate_features_for_inpatient_admissions.py

Seems to be related to test and train sets not matching in the number of categorical columns

**Comment by HLasse** [comment]
The error is related to integer values (sometimes) being interpreted as categorical by deepchecks. If the column is ambiguous and the categories/integer values are different across splits, deepchecks can sometimes be confused and will raise an error. 

This happens e.g. when counting the number of f3 diagnoses within 31 days. 
For each value above ~10, only 1-3 patients receive that many diagnoses. The integer values have different ranges in test/train as well.

A couple of options as I see it:
1. Handle rare values in TSFlattener: add an option for collapsing values greater than N to be X (e.g. all patients with more than 10 diagnoses within 30 days would be set to 10)
2. Write our own handler for determining when a column is categorical or not to feed to deepchecks.
3. Skip deepchecks split checks if the error occurs.

This specific error currently occurs for approximately 30 columns in Erik and Jakob's feature generation.

 Thoughts, @erikperfalk, @MartinBernstorff, @KennethEnevoldsen?

**Comment by bokajgd** [comment]
I'll try resolving this by informing deepchecks that the data never contains categorical features (option 2).

**Comment by KennethEnevoldsen** [comment]
That is a good solution @bokajgd. Lasse and I talked about that for any of these long-tailed distributions, it might be ideal to log transform them, that doesn't really solve the general problem, but simply wanted to let you know that it might be relevant during the preprocessing pipeline.
