### ISSUE TITLE
Split out timeseriesflattener

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-feature-generation#99]
Have assigned you, Martin, as this will primarily break code that you have written.

Our suggestion is to move the loaders into the `applications` folder and add a readme.

**Comment by KennethEnevoldsen** [comment]
It might also be worth moving them to psycop-ml-utils?

**Comment by MartinBernstorff** [comment]
I'd suggest mving timeseriesflattener into its own repo - that way we'll stil have a "repo for feature generation in psycop", but extract the generalise-able code to its own location :-)

**Comment by KennethEnevoldsen** [comment]
Def. a possibility (if we keep the git history).

**Comment by MartinBernstorff** [comment]
Ah yeah, that's super important 👍

**Comment by KennethEnevoldsen** [comment]
Moved w. git history:
https://github.com/Aarhus-Psychiatry-Research/timeseriesflattener/pull/7
